### ISSUE TITLE
EXT:yag 

### ISSUE THREAD

**Issue by FaraFara** [punktDe/pt_extbase#10]
ext:YAG don't work correct after EXT:Flux installing.
After iam uninstall flux, YAG work correct again.

iam open issue in ext:flux development branch:
https://github.com/FluidTYPO3/flux/issues/532

.... and this is his comment:
https://github.com/FluidTYPO3/flux/issues/532#issuecomment-40882837

Please resolve this issue

**Comment by daniellienert** [comment]
That should be fixed in the meanwhile. Can anyone confirm that?

**Comment by FaraFara** [comment]
Yes, this problem solved
