### ISSUE TITLE
Fatal error in front end view of album

### ISSUE THREAD

**Issue by ziegenberg** [punktDe/pt_extbase#12]
I created a gallery with an album, included the plugin in a page and want to show an album with the lightbox theme. The first page is showed nicely, but when I click "next" in the pager, I get an fatal error:

> Fatal error: Declaration of Tx_PtExtbase_Controller_AbstractActionController::processRequest() must be compatible with TYPO3\CMS\Extbase\Mvc\Controller\ControllerInterface::processRequest(TYPO3\CMS\Extbase\Mvc\RequestInterface $request, TYPO3\CMS\Extbase\Mvc\ResponseInterface $response) in /www/htdocs/w00ccc62/typo3/htdocs/typo3conf/ext/pt_extbase/Classes/Controller/AbstractActionController.php on line 255

The referenced function in `pt_extbase/Classes/Controller/AbstractActionController.php` reads:

```` php
public function processRequest(Tx_Extbase_MVC_RequestInterface $request, Tx_Extbase_MVC_ResponseInterface $response) {
	parent::processRequest($request, $response);
	
	if(TYPO3_MODE === 'BE') {
		// if we are in BE mode, this ist the last line called
		$this->lifecycleManager->updateState(Tx_PtExtbase_Lifecycle_Manager::END);
	}
}
````

When I change the function signature to 

```` php
public function processRequest(\TYPO3\CMS\Extbase\Mvc\RequestInterface $request, \TYPO3\CMS\Extbase\Mvc\ResponseInterface $response) {
	parent::processRequest($request, $response);
	
	if(TYPO3_MODE === 'BE') {
		// if we are in BE mode, this ist the last line called
		$this->lifecycleManager->updateState(Tx_PtExtbase_Lifecycle_Manager::END);
	}
}
````

it works. Does this make any sense?

The same problem is also mentioned [here] (https://www.mail-archive.com/typo3-english@lists.typo3.org/msg24224.html) and [here] (https://forge.typo3.org/issues/51036).

**Comment by daniellienert** [comment]
Please check if you have the latest versions of the extensions yag / pt_extlist and pt_extbase
