### ISSUE TITLE
Scheduler problem caused by pt_extbase 2.0.0 or pt_extlist 2.0.0 

### ISSUE THREAD

**Issue by gudro55** [punktDe/pt_extbase#13]
Hi,
I tried to install pt_extlist 2.0.0 and pt_extbase 2.0.0 and these extensions make problem with scheduler.

For example, I can't create a scheduled task when these extensions are installed.

**Comment by larp-welt** [comment]
Hi!

I can confirm the problem with pt_extbase. It is the same error as described for the crawler in this link:

https://forge.typo3.org/issues/60207

But to be honest: I'm using Typo3 V7.0.2

Bye

**Comment by daniellienert** [comment]
Hey Guys, 
sorry for that issue. It is fixed on git / master for weeks. I hope to mange to update the repository shortly. In the meantime you can use the code from master.

Cheers, 
Daniel
