### ISSUE TITLE
Backend.css can't be loaded if TYPO3 runs in subdirectory

### ISSUE THREAD

**Issue by liayn** [punktDe/pt_extbase#14]
siteurl: http://example.com/master/
requested url: http://example.com/typo3conf/ext/pt_extbase/Resources/Public/CSS/Backend.css

**Comment by daniellienert** [comment]
Does this issue still exists? Can you give me some more details?

**Comment by liayn** [comment]
Yes it does.
Simply open the BE and check your browser's console - network panel - and see the 404 response.
As denoted above, the instance runs in a subfolder of the webroot, but the CSS is included from webroot, which is wrong.

**Comment by DavidBruchmann** [comment]
I can confirm this issue.

**Comment by DavidBruchmann** [comment]
Actually I've another problem with it:, it tries ot load: 
 
http://domain.com/typo3/typo3conf/ext/pt_extbase/Resources/Public/CSS/Backend.css

**Comment by DavidBruchmann** [comment]
Like this in ext_tables.php it works:


```
// Custom CSS include
if (TYPO3_MODE=="BE") {
    $extRelPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath('pt_extbase');
    $TBE_STYLES['inDocStyles_TBEstyle'] .= '@import "'.$extRelPath.'Resources/Public/CSS/Backend.css";';
}

```

**Comment by DavidBruchmann** [comment]
Amazing, my old comment is still usable, good hint, David 😀
