### ISSUE TITLE
AjaxDispatcher support for namespaced controllers?

### ISSUE THREAD

**Issue by edrush** [punktDe/pt_extbase#17]
If I understand correctly, the *eIDDispatcher.php* does currently not support namespaced controllers - correct? Are there plans to do so?

**Comment by daniellienert** [comment]
It does. You have to provide the vendor name. This is done by prefixing the extension name with a dot, like: `vendorName.extensionName`.

Cheers,
Daniel

**Comment by edrush** [comment]
Works great, thank you!

**Comment by woodyc79** [comment]
Sehr geehrte Damen und Herren!

Ich bin ab 3.3 wieder für Sie da.

Mit freundlichen Grüßen,
Christian Holzmann


-- 


      Christian Holzmann, MSc
      New Media/Web Management, Development & Consulting
      Certified TYPO3 Integrator
      
      innovations ☆ Agentur für neue Medien 
            
      ⌂ Kupferbrunnstrasse 21 | 3100 St. Pölten
      ✆ +43 (0) 676 533 1375
      
      ✉ mail@innovations.at
      ⊙ http://www.innovations.at
      ⊙ https://www.xing.com/profile/Christian_Holzmann
